export * from "./CanvasPreloader";
export * from "./CanvasHeader";
export * from "./CanvasHero";
export * from "./CanvasAbout";
export * from "./CanvasAcademics";
export * from "./CanvasWorks";
export * from "./CanvasServices";
export * from "./CanvasContact";
export * from "./CanvasToolbar";
